mybatis:
  mapper-locations: classpath*:mapper/**/**Mapper.xml
spring:
  application:
    name: autowechat
  profiles:
    active: test
  datasource: #数据源配置在bootstrap.yml启动报错，why？
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 123456
    url: jdbc:log4jdbc:sqlite::resource:wechat.db?date_string_format=yyyy-MM-dd HH:mm:ss
wechat:
  auto-chat-prefix: 宝
  auto-chat-suffix: 【不是自动回复】
  app-version: 1.0
  login-title: 微信登录
  base-path: /weixin
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
  special-user: filehelper, weibo,qqmail, fmessage, tmessage, qmessage, qqsync, floatbottle, lbsapp, shakeapp, medianote,qqfriend, readerapp, blogapp, facebookapp, masssendapp, meishiapp, feedsapp, voip,blogappweixin, brandsessionholder, weixinreminder, officialaccounts, wxitil,notification_messages, wxid_novlwrv3lqwv11, gh_22b87fa7cb3c, userexperience_alarm
openai:
  openai_key: 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
  expire: 60