mybatis:
  mapper-locations: classpath*:mapper/**/**Mapper.xml
spring:
  application:
    name: autowechat
  profiles:
    active: test
  datasource: #数据源配置在bootstrap.yml启动报错，why？
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 123456
    url: jdbc:log4jdbc:sqlite:D:/weixin/wechat.db?date_string_format=yyyy-MM-dd HH:mm:ss
