spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 123456
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/wechat?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
  boot:
    #admin客户端注册到admin 服务
    admin:
      client:
        url: http://localhost:8999
        period: 1000
        read-timeout: 5000
mybatis:
  mapper-locations: classpath*:mapper/**/**Mapper.xml

server:
  port: 9999

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: ["*"]
